export default {
    Home:"Home",
    Otp:  "Otp",
    Wellcome:  "Wellcome",
    Login:  "Login",
    Payment:"Payment",
    Successfulpayment:"Successfulpayment",
    Category:"Category",
    SubCategory:"SubCategory",
    Addmobile:"Addmobile",
    Poductdetils:"Poductdetils",
    Setting:"Setting",
    Cartscreen:  "Cartscreen", 
    Wallet:  "Wallet", 
    Trackorder:  "Trackorder", 
    Order:  "Order", 
    Support:  "Support", 
    Myprofile:  "Myprofile", 
    Orderconfirm:  "Orderconfirm", 
    AddAddress:  "AddAddress",
    Address:  "Address",
    Aboutus:  "Aboutus",
    Signup:"Signup",
    Search:"Search",
    Product:"Product",
    GooglePlacesInput:"GooglePlacesInput",
    Notification:"Notification",
    WalletSeeAll:"WalletSeeAll"
}